
```{r}
install.packages('RSiena')
library(RSiena)
friend.data.w1 <- s501
friend.data.w2 <- s502
friend.data.w3 <- s503
drink <- s50a
smoke <- s50s
friendship <- sienaDependent(array(c(friend.data.w1, friend.data.w2, friend.data.w3), dim = c(50, 50,
    3)))
smoke1 <- coCovar(smoke[, 1])
alcohol <- varCovar(drink)
mydata <- sienaDataCreate(friendship, smoke1, alcohol)
# and request
mydata
# to see what you have produced.
```

```{r}
myalgorithm <- sienaAlgorithmCreate(projname = "s50_3")
```
```{r}
myeff <- getEffects(mydata)
myeff <- includeEffects(myeff, transTrip, cycle3)
myeff <- includeEffects(myeff, egoX, altX, egoXaltX, interaction1 = "alcohol")
myeff <- includeEffects(myeff, simX, interaction1 = "smoke1")
myeff
```

```{r}
ans <- siena07(myalgorithm, data = mydata, effects = myeff)
```

```{r}
summary(ans)
```

```{r}
myeff <- setEffect(myeff, inPopSqrt, fix = TRUE, test = TRUE, initialValue = 0)
```

```{r}
myeff <- setEffect(myeff, inPopSqrt, fix = FALSE, test = TRUE, initialValue = 0)

```

```{r}
ans <- siena07(myalgorithm, data = mydata, effects = myeff)

```

