---
title: "Research Question 1"
#bibliography: references.bib
author: "Daphne Janssen"
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r Sys.time()`

<!---
Last compiled on `r format(Sys.time(), '%B, %Y')`
--->

<br>

----

# Research Question week 1

<br>

*To what extent is there a difference between men and women within Sociology and Engineering in (1) who they work with and (2) which topics they study compared to three universities within the Netherlands?*




